// Only labels introduced by the approved UI. The editorial rewrite is a separate proposal.
const keys=['sources','measure','method','source','limits','share','copy','copied','failed','hide','show','details','compare','explore','close','choose','noData','reading','location','link','summary'];
const rows={
 en:['Sources & method','What this measures','Reference, model & scenario','Data source','Limits','Share view','Copy link','Link copied','Could not copy. Select the link below.','Hide layer','Show layer','Reading details','Compare years','Explore location','Close','Choose a filter to see its data','No estimate available','Map reading','Location','View link','Map summary'],
 fr:['Sources et méthode','Ce qui est mesuré','Référence, modèle et scénario','Source des données','Limites','Partager la vue','Copier le lien','Lien copié','Copie impossible. Sélectionnez le lien ci-dessous.','Masquer le calque','Afficher le calque','Détails de lecture','Comparer les années','Explorer le lieu','Fermer','Choisissez un filtre pour voir ses données','Estimation indisponible','Lecture de la carte','Lieu','Lien de la vue','Synthèse de la carte'],
 es:['Fuentes y método','Qué se mide','Referencia, modelo y escenario','Fuente de datos','Limitaciones','Compartir vista','Copiar enlace','Enlace copiado','No se pudo copiar. Selecciona el enlace de abajo.','Ocultar capa','Mostrar capa','Detalles de lectura','Comparar años','Explorar lugar','Cerrar','Elige un filtro para ver sus datos','Estimación no disponible','Lectura del mapa','Lugar','Enlace de la vista','Resumen del mapa'],
 it:['Fonti e metodo','Cosa viene misurato','Riferimento, modello e scenario','Fonte dei dati','Limiti','Condividi vista','Copia link','Link copiato','Copia non riuscita. Seleziona il link qui sotto.','Nascondi livello','Mostra livello','Dettagli di lettura','Confronta gli anni','Esplora il luogo','Chiudi','Scegli un filtro per vedere i dati','Stima non disponibile','Lettura della mappa','Luogo','Link della vista','Sintesi della mappa'],
 vi:['Nguồn dữ liệu và phương pháp','Chỉ số đo lường','Mốc tham chiếu, mô hình và kịch bản','Nguồn dữ liệu','Giới hạn','Chia sẻ góc nhìn','Sao chép liên kết','Đã sao chép liên kết','Không thể sao chép. Hãy chọn liên kết bên dưới.','Ẩn lớp dữ liệu','Hiện lớp dữ liệu','Chi tiết chỉ số','So sánh các năm','Khám phá địa điểm','Đóng','Chọn bộ lọc để xem dữ liệu','Không có ước tính','Cách đọc bản đồ','Địa điểm','Liên kết góc nhìn','Tóm tắt bản đồ'],
 ja:['出典と方法','測定する内容','基準期間・モデル・シナリオ','データの出典','限界','表示を共有','リンクをコピー','リンクをコピーしました','コピーできませんでした。下のリンクを選択してください。','レイヤーを非表示','レイヤーを表示','数値の詳細','年を比較','場所を詳しく見る','閉じる','指標を選んでデータを表示','推計値なし','地図の表示方法','場所','表示のリンク','地図の概要'],
 zh:['来源与方法','测量内容','基准、模型与情景','数据来源','局限','分享视图','复制链接','链接已复制','无法复制。请选择下方链接。','隐藏图层','显示图层','读数详情','比较年份','探索地点','关闭','选择指标以查看数据','暂无估算','地图读数','地点','视图链接','地图摘要'],
 'zh-Hant':['來源與方法','測量內容','基準、模型與情境','資料來源','限制','分享視圖','複製連結','連結已複製','無法複製。請選取下方連結。','隱藏圖層','顯示圖層','讀數詳情','比較年份','探索地點','關閉','選擇指標以查看資料','暫無估算','地圖讀數','地點','視圖連結','地圖摘要']
};
export const experienceUICopy=lang=>Object.fromEntries(keys.map((key,i)=>[key,(rows[lang]||rows.en)[i]]));
