import {humanCopy} from './human-impact-copy.mjs';
import {formatHoverNumber} from './hover-diagnostic.mjs';

const headlineKeys=['heatMore','heatLess','warmingMore','warmingLess','fireMore','fireLess','dry','coastMore','coastLess','coastSame','riverMore','riverLess','riverSame','population','summerReference','fireReference','climateReference','floodReference','populationReference'];
const headlines={
 en:['The hottest month could be {n} °C warmer on average','The hottest month could be {n} °C cooler on average','Air over land could be {n} °C warmer on average','Air over land could be {n} °C cooler on average','On average, {n} extra days a year of fire weather','On average, {n} fewer days a year of fire weather','{n}% of mapped land could become drier','Coastal flood zones could expand','Coastal flood zones could shrink','The coastal flood estimate is unchanged','River flood zones could expand','River flood zones could shrink','The river flood estimate is unchanged','About {n} billion people worldwide','Compared with past summers.','Compared with past fire weather.','Compared with the past climate.','Model estimate, compared with past conditions.','UN population projection.'],
 fr:['Le mois le plus chaud pourrait gagner {n} °C en moyenne','Le mois le plus chaud pourrait perdre {n} °C en moyenne','Sur les terres, {n} °C de plus en moyenne','Sur les terres, {n} °C de moins en moyenne','En moyenne, {n} jours de plus par an favorables aux incendies','En moyenne, {n} jours de moins par an favorables aux incendies','{n} % des terres cartographiées pourraient devenir plus sèches','Les zones inondables sur les côtes pourraient s’étendre','Les zones inondables sur les côtes pourraient se réduire','L’estimation des inondations côtières reste la même','Les zones inondables près des fleuves pourraient s’étendre','Les zones inondables près des fleuves pourraient se réduire','L’estimation des crues reste la même','Environ {n} milliards d’habitants sur Terre','Par rapport aux étés d’autrefois.','Par rapport à la météo des incendies d’autrefois.','Par rapport au climat d’autrefois.','Selon le modèle, comparé aux conditions d’autrefois.','Projection de population de l’ONU.'],
 es:['El mes más caluroso podría ser {n} °C más cálido de media','El mes más caluroso podría ser {n} °C más fresco de media','El aire sobre tierra podría ser {n} °C más cálido de media','El aire sobre tierra podría ser {n} °C más fresco de media','De media, {n} días más al año de tiempo favorable a incendios','De media, {n} días menos al año de tiempo favorable a incendios','El {n}% de la tierra cartografiada podría volverse más seca','Las zonas inundables de la costa podrían ampliarse','Las zonas inundables de la costa podrían reducirse','La estimación de inundación costera no cambia','Las zonas inundables junto a ríos podrían ampliarse','Las zonas inundables junto a ríos podrían reducirse','La estimación de inundación fluvial no cambia','Unos {n} mil millones de personas en el mundo','Comparado con los veranos del pasado.','Comparado con el tiempo favorable a incendios del pasado.','Comparado con el clima del pasado.','Estimación del modelo, comparada con las condiciones pasadas.','Proyección de población de la ONU.'],
 it:['Il mese più caldo potrebbe essere in media {n} °C più caldo','Il mese più caldo potrebbe essere in media {n} °C più fresco','L’aria sulla terraferma potrebbe essere {n} °C più calda in media','L’aria sulla terraferma potrebbe essere {n} °C più fresca in media','In media, {n} giorni in più all’anno di meteo favorevole agli incendi','In media, {n} giorni in meno all’anno di meteo favorevole agli incendi','Il {n}% delle terre mappate potrebbe diventare più secco','Le zone costiere allagabili potrebbero estendersi','Le zone costiere allagabili potrebbero ridursi','La stima delle inondazioni costiere non cambia','Le zone allagabili lungo i fiumi potrebbero estendersi','Le zone allagabili lungo i fiumi potrebbero ridursi','La stima delle piene fluviali non cambia','Circa {n} miliardi di persone nel mondo','Rispetto alle estati del passato.','Rispetto al meteo favorevole agli incendi del passato.','Rispetto al clima del passato.','Stima del modello, rispetto alle condizioni passate.','Proiezione demografica dell’ONU.'],
 vi:['Tháng nóng nhất có thể nóng hơn trung bình {n} °C','Tháng nóng nhất có thể mát hơn trung bình {n} °C','Không khí trên đất liền có thể nóng hơn trung bình {n} °C','Không khí trên đất liền có thể mát hơn trung bình {n} °C','Trung bình thêm {n} ngày mỗi năm có thời tiết thuận lợi cho cháy','Trung bình ít hơn {n} ngày mỗi năm có thời tiết thuận lợi cho cháy','{n}% vùng đất trên bản đồ có thể khô hơn','Vùng có thể ngập ven biển có thể mở rộng','Vùng có thể ngập ven biển có thể thu hẹp','Ước tính ngập ven biển không đổi','Vùng có thể ngập gần sông có thể mở rộng','Vùng có thể ngập gần sông có thể thu hẹp','Ước tính lũ sông không đổi','Khoảng {n} tỷ người trên thế giới','So với mùa hè trước đây.','So với thời tiết thuận lợi cho cháy trước đây.','So với khí hậu trước đây.','Ước tính từ mô hình, so với điều kiện trước đây.','Dự báo dân số của LHQ.'],
 ja:['最も暑い月が平均{n} °C暑くなる可能性','最も暑い月が平均{n} °C涼しくなる可能性','陸上の気温が平均{n} °C上がる可能性','陸上の気温が平均{n} °C下がる可能性','火災を招く気象の日が年平均{n}日増える可能性','火災を招く気象の日が年平均{n}日減る可能性','地図上の陸域の{n}%が乾燥化する可能性','沿岸の浸水想定域が広がる可能性','沿岸の浸水想定域が縮まる可能性','沿岸洪水の推計に変化なし','河川の浸水想定域が広がる可能性','河川の浸水想定域が縮まる可能性','河川洪水の推計に変化なし','世界の人口は約{n}億人','過去の夏との比較。','過去の火災を招く気象との比較。','過去の気候との比較。','過去の条件と比べたモデル推計。','国連の人口推計。'],
 zh:['最热月份可能平均升温{n} °C','最热月份可能平均降温{n} °C','陆地上空的气温可能平均升高{n} °C','陆地上空的气温可能平均降低{n} °C','每年平均可能多{n}天易发火灾的天气','每年平均可能少{n}天易发火灾的天气','地图上{n}%的陆地可能变得更干燥','沿海可能受淹的区域或将扩大','沿海可能受淹的区域或将缩小','沿海洪水估计不变','河流附近可能受淹的区域或将扩大','河流附近可能受淹的区域或将缩小','河流洪水估计不变','全球人口约{n}亿','与过去的夏季相比。','与过去的火险天气相比。','与过去的气候相比。','模型估计，与过去的条件相比。','联合国人口预测。'],
 'zh-Hant':['最熱月份可能平均升溫{n} °C','最熱月份可能平均降溫{n} °C','陸地上空的氣溫可能平均升高{n} °C','陸地上空的氣溫可能平均降低{n} °C','每年平均可能多{n}天易發火災的天氣','每年平均可能少{n}天易發火災的天氣','地圖上{n}%的陸地可能變得更乾燥','沿海可能受淹的區域或將擴大','沿海可能受淹的區域或將縮小','沿海洪水估計不變','河川附近可能受淹的區域或將擴大','河川附近可能受淹的區域或將縮小','河川洪水估計不變','全球人口約{n}億','與過去的夏季相比。','與過去的火險天氣相比。','與過去的氣候相比。','模型估計，與過去的條件相比。','聯合國人口推估。'],
};
const dataKeys=['measureLabel','comparisonLabel','valuesLabel','more','past','pastFlood','selected','difference','days','points','pastComparison','floodComparison','land','burnable','floodShare','dryShare','populationMeasure','populationMedium','billion','noData','area','change','historicalMode','valueMode','cooler','same','warmer','fewer','moreDays','wetter','drier','lessFlood','moreFlood','growing','shrinking','lessDecline','moreDecline','populationCaption'];
const dataRows={
 en:['What this filter shows','What it is compared with','Values behind the map summary','Sources, calculations and limits','Past average','Past model reference','Selected year','Difference','days/year','percentage points','Here, “past” means the {period} average.','Here, “past” means the flood model’s reference for {period}.','Average over land with data.','Average over modelled land that can burn.','Flood-prone share of model grid cells, for a rare flood deeper than 0.5 m.','{n}% of land with data has a drier climate index.','Total of UN country and area projections. The map highlights countries losing population.','UN medium projection','billion people','No estimate available','An estimate for this area.','Change since 2026','Past climate','Estimated conditions','Cooler','No change','Warmer','Fewer days','More days','Wetter','Drier','Less flood-prone','More flood-prone','Growing','Shrinking','Less decline','More decline','Countries losing population'],
 fr:['Ce que ce filtre montre','À quoi on le compare','Valeurs de la synthèse de la carte','Sources, calculs et limites','Moyenne passée','Référence passée du modèle','Année choisie','Différence','jours/an','points de pourcentage','Ici, « autrefois » correspond à la moyenne {period}.','Ici, « autrefois » correspond à la référence du modèle de crues pour {period}.','Moyenne sur les terres avec données.','Moyenne sur les terres modélisées pouvant brûler.','Part inondable des cellules du modèle, pour une crue rare dépassant 0,5 m.','{n} % des terres avec données ont un indice de climat plus sec.','Total des projections de pays et territoires de l’ONU. La carte montre les pays où la population diminue.','Scénario moyen de l’ONU','milliards d’habitants','Estimation indisponible','Estimation pour cette zone.','Changement depuis 2026','Climat d’autrefois','Conditions estimées','Plus froid','Sans changement','Plus chaud','Moins de jours','Plus de jours','Plus humide','Plus sec','Moins inondable','Plus inondable','Augmente','Diminue','Faible baisse','Forte baisse','Pays où la population diminue'],
 es:['Qué muestra este filtro','Con qué se compara','Valores del resumen del mapa','Fuentes, cálculos y límites','Media pasada','Referencia pasada del modelo','Año elegido','Diferencia','días/año','puntos porcentuales','Aquí, «pasado» significa la media de {period}.','Aquí, «pasado» significa la referencia del modelo de inundaciones de {period}.','Media de la tierra con datos.','Media de las tierras modelizadas que pueden arder.','Proporción de celdas inundables, para una inundación poco frecuente de más de 0,5 m.','El {n}% de la tierra con datos tiene un índice climático más seco.','Total de proyecciones de países y territorios de la ONU. El mapa destaca países que pierden población.','Proyección media de la ONU','mil millones de personas','No hay estimación','Estimación para esta zona.','Cambio desde 2026','Clima pasado','Condiciones estimadas','Más fresco','Sin cambio','Más cálido','Menos días','Más días','Más húmedo','Más seco','Menos inundable','Más inundable','Aumenta','Disminuye','Menor descenso','Mayor descenso','Países que pierden población'],
 it:['Cosa mostra questo filtro','Con cosa viene confrontato','Valori della sintesi della mappa','Fonti, calcoli e limiti','Media passata','Riferimento passato del modello','Anno scelto','Differenza','giorni/anno','punti percentuali','Qui, «passato» indica la media del {period}.','Qui, «passato» indica il riferimento del modello di piena per il {period}.','Media delle terre con dati.','Media delle terre modellizzate che possono bruciare.','Quota di celle allagabili, per una rara piena con oltre 0,5 m d’acqua.','Il {n}% delle terre con dati ha un indice climatico più secco.','Totale delle proiezioni ONU di paesi e territori. La mappa evidenzia i paesi che perdono popolazione.','Proiezione media ONU','miliardi di persone','Stima non disponibile','Stima per questa zona.','Variazione dal 2026','Clima passato','Condizioni stimate','Più fresco','Nessuna variazione','Più caldo','Meno giorni','Più giorni','Più umido','Più secco','Meno allagabile','Più allagabile','Cresce','Diminuisce','Calo minore','Calo maggiore','Paesi che perdono popolazione'],
 vi:['Bộ lọc này thể hiện gì','Được so sánh với gì','Số liệu của bản đồ tổng hợp','Nguồn, cách tính và giới hạn','Trung bình trước đây','Mốc trước đây của mô hình','Năm đã chọn','Chênh lệch','ngày/năm','điểm phần trăm','Ở đây, «trước đây» là trung bình giai đoạn {period}.','Ở đây, «trước đây» là mốc của mô hình lũ cho giai đoạn {period}.','Trung bình vùng đất có dữ liệu.','Trung bình vùng đất mô hình có thể cháy.','Tỷ lệ ô mô hình có thể ngập, trong lũ hiếm gặp sâu hơn 0,5 m.','{n}% vùng đất có dữ liệu có chỉ số khí hậu khô hơn.','Tổng dự báo dân số các quốc gia và vùng lãnh thổ của LHQ. Bản đồ đánh dấu nơi dân số giảm.','Phương án trung bình của LHQ','tỷ người','Không có ước tính','Ước tính cho khu vực này.','Thay đổi từ 2026','Khí hậu trước đây','Điều kiện ước tính','Mát hơn','Không đổi','Nóng hơn','Ít ngày hơn','Nhiều ngày hơn','Ẩm hơn','Khô hơn','Ít ngập hơn','Dễ ngập hơn','Tăng','Giảm','Giảm ít hơn','Giảm nhiều hơn','Các nước có dân số giảm'],
 ja:['この指標が示すこと','比較の基準','地図の集計値の内訳','出典・計算・限界','過去の平均','モデルの過去の基準','選んだ年','差','日/年','パーセントポイント','ここで「過去」とは{period}年の平均です。','ここで「過去」とは洪水モデルの{period}年の基準です。','データのある陸域の平均。','燃焼可能なモデル陸域の平均。','まれな洪水で浸水深が0.5mを超えるモデル格子の割合。','データのある陸域の{n}%で気候指数がより乾燥した値に。','国連の各国・地域の推計の合計。地図は人口が減る国を示します。','国連中位推計','億人','推計値なし','この地域の推計。','2026年からの変化','過去の気候','推計される状況','より涼しい','変化なし','より暑い','日数が少ない','日数が多い','より湿潤','より乾燥','浸水しにくい','浸水しやすい','増加','減少','小さい減少','大きい減少','人口が減る国'],
 zh:['这个指标显示什么','比较基准是什么','地图汇总值的构成','来源、计算与局限','过去的平均值','模型的过去基准','所选年份','差值','天/年','个百分点','这里的“过去”指{period}年的平均值。','这里的“过去”指洪水模型在{period}年的基准。','有数据陆地的平均值。','模型中可燃陆地的平均值。','罕见洪水中水深超过0.5米的模型网格占比。','有数据陆地的{n}%呈现更干燥的气候指数。','联合国各国和地区人口预测的总和。地图标出人口减少的国家。','联合国中位方案','亿人','暂无估计','此区域的估计。','相较2026年的变化','过去气候','估计状况','更凉','无变化','更热','天数更少','天数更多','更湿润','更干燥','较不易淹水','较易淹水','增长','减少','降幅较小','降幅较大','人口减少的国家'],
 'zh-Hant':['這個指標顯示什麼','比較基準是什麼','地圖彙總值的構成','來源、計算與限制','過去的平均值','模型的過去基準','所選年份','差值','天/年','個百分點','這裡的「過去」指{period}年的平均值。','這裡的「過去」指洪水模型在{period}年的基準。','有資料陸地的平均值。','模型中可燃陸地的平均值。','罕見洪水中水深超過0.5公尺的模型網格占比。','有資料陸地的{n}%呈現更乾燥的氣候指數。','聯合國各國和地區人口推估的總和。地圖標出人口減少的國家。','聯合國中位方案','億人','暫無估計','此區域的估計。','相較2026年的變化','過去氣候','估計狀況','更涼','無變化','更熱','天數更少','天數更多','更濕潤','更乾燥','較不易淹水','較易淹水','增長','減少','降幅較小','降幅較大','人口減少的國家'],
};
const record=(keys,rows,locale)=>Object.fromEntries(keys.map((key,i)=>[key,(rows[locale]||rows.en)[i]]));
const historicalLabels={en:'Compared with the past',fr:'Par rapport au passé',es:'Comparado con el pasado',it:'Rispetto al passato',vi:'So với trước đây',ja:'過去との比較',zh:'与过去相比','zh-Hant':'與過去相比'};
const localRows={
 en:['Values for this area','Compared with the estimate for {year}.','Estimated population of this country.'],
 fr:['Valeurs pour cette zone','Par rapport à l’estimation pour {year}.','Population estimée de ce pays.'],
 es:['Valores de esta zona','Comparado con la estimación para {year}.','Población estimada de este país.'],
 it:['Valori di questa zona','Rispetto alla stima per il {year}.','Popolazione stimata di questo paese.'],
 vi:['Số liệu cho khu vực này','So với ước tính cho năm {year}.','Dân số ước tính của quốc gia này.'],
 ja:['この地域の値','{year}年の推計との比較。','この国の推計人口。'],
 zh:['此区域的数值','与{year}年的估计相比。','这个国家的估计人口。'],
 'zh-Hant':['此區域的數值','與{year}年的估計相比。','這個國家的估計人口。'],
};
export const readingCopy=locale=>({...record(dataKeys,dataRows,locale),...record(['localValues','yearComparison','countryPopulation'],localRows,locale),historicalMode:historicalLabels[locale]||historicalLabels.en});
const presentHeat={
 en:['The hottest month has become {n} °C warmer on average','The hottest month has become {n} °C cooler on average','Model estimate for 2026, compared with 1970–2000.'],
 fr:['Le mois le plus chaud a gagné {n} °C en moyenne','Le mois le plus chaud a perdu {n} °C en moyenne','Selon le modèle pour 2026, par rapport à 1970–2000.'],
 es:['El mes más caluroso ha subido {n} °C de media','El mes más caluroso ha bajado {n} °C de media','Estimación del modelo para 2026, comparada con 1970–2000.'],
 it:['Il mese più caldo è diventato in media {n} °C più caldo','Il mese più caldo è diventato in media {n} °C più fresco','Stima del modello per il 2026, rispetto al 1970–2000.'],
 vi:['Tháng nóng nhất đã nóng hơn trung bình {n} °C','Tháng nóng nhất đã mát hơn trung bình {n} °C','Ước tính từ mô hình cho năm 2026, so với 1970–2000.'],
 ja:['最も暑い月は平均{n} °C暑くなりました','最も暑い月は平均{n} °C涼しくなりました','1970–2000年と比較した2026年のモデル推計。'],
 zh:['最热月份已平均升温{n} °C','最热月份已平均降温{n} °C','2026年的模型估计，与1970–2000年相比。'],
 'zh-Hant':['最熱月份已平均升溫{n} °C','最熱月份已平均降溫{n} °C','2026年的模型估計，與1970–2000年相比。'],
};
export function overviewCopy(filter,reading,locale,year){
 const c=record(headlineKeys,headlines,locale),n=(v,d=1)=>formatHoverNumber(v,locale,false,d);
 const more=reading.value>=0,sign=reading.value===0?'Same':more?'More':'Less';
 const key={chaleur:'heat'+(more?'More':'Less'),stabilite:'warming'+(more?'More':'Less'),feux:'fire'+(more?'More':'Less'),secheresse:'dry',mer:'coast'+sign,fleuves:'river'+sign,declin:'population'}[filter];
 const eastAsian=['ja','zh','zh-Hant'].includes(locale);
 const value=filter==='declin'?reading.value/(eastAsian?1e8:1e9):Math.abs(reading.value);
 const currentHeat=filter==='chaleur'&&year===2026?(presentHeat[locale]||presentHeat.en):null;
 return {headline:(currentHeat?currentHeat[more?0:1]:c[key]).replace('{n}',n(value,['feux','secheresse'].includes(filter)?0:1)),reference:currentHeat?currentHeat[2]:c[filter==='declin'?'populationReference':['mer','fleuves'].includes(filter)?'floodReference':filter==='chaleur'?'summerReference':filter==='feux'?'fireReference':'climateReference'],detail:humanCopy(locale).effects[filter]};
}
export function explainSummary(filter,reading,locale,year){
 if(!reading?.available||!Number.isFinite(reading.value)||!humanCopy(locale).names[filter])return null;
 const c=readingCopy(locale),human=humanCopy(locale),flood=['mer','fleuves'].includes(filter);
 const n=(v,d=2)=>formatHoverNumber(v,locale,false,d),period=reading.referencePeriod.join('–');
 let values;
 if(['chaleur','stabilite','feux','mer','fleuves'].includes(filter)){
  const unit=flood?'%':filter==='feux'?c.days:'°C';
  values=`${flood?c.pastFlood:c.past} (${period}): ${n(reading.referenceValue)} ${unit}\n${c.selected} (${year}): ${n(reading.estimateValue)} ${unit}\n${c.difference}: ${formatHoverNumber(reading.value,locale,true,2)} ${flood?c.points:unit}`;
 }else if(filter==='secheresse')values=c.dryShare.replace('{n}',n(reading.value,1));
 else values=`${c.selected} (${year}): ${n(reading.value/(['ja','zh','zh-Hant'].includes(locale)?1e8:1e9))} ${c.billion}\n${c.populationMedium}`;
 return {...c,measure:filter==='declin'?c.populationMeasure:flood?c.floodShare:[human.definitions[filter],filter==='feux'?c.burnable:c.land].join(' '),comparison:filter==='declin'?'':c[flood?'floodComparison':'pastComparison'].replace('{period}',period),values};
}
// A pinned map reading belongs to one model cell (or one country for
// population). Keep it separate from the area-weighted world overview.
export function explainMapReading(filter,reading,locale,year,mode){
 if(!reading?.available||!Number.isFinite(reading.value))return null;
 if(filter==='declin'&&(!(reading.value>0)||!(reading.baseline>0)))return null;
 const c=readingCopy(locale),human=humanCopy(locale),flood=['mer','fleuves'].includes(filter);
 const n=v=>formatHoverNumber(v,locale,false,filter==='declin'?0:2);
 const unit=flood?'%':filter==='feux'?c.days:filter==='secheresse'?'De Martonne':filter==='declin'?'':'°C';
 const historical=mode==='reference',changing=mode==='change',period=reading.historicalPeriod?.join('–');
 const reference=historical?reading.historical:reading.baseline;
 const comparedYear=filter==='declin'?(changing?2026:2025):2026;
 const comparison=filter==='declin'||changing?c.yearComparison.replace('{year}',comparedYear)
  :historical||filter==='stabilite'?c[flood?'floodComparison':'pastComparison'].replace('{period}',period):'';
 const lines=[`${c.selected} (${year}): ${n(reading.value)} ${unit}`.trim()];
 if(filter==='declin'||historical||changing){
  if(!Number.isFinite(reference))return null;
  // Warming is already an anomaly: zero is not an absolute past temperature.
  if(!(filter==='stabilite'&&historical))lines.unshift(`${historical?(flood?c.pastFlood:c.past):c.selected} (${historical?period:comparedYear}): ${n(reference)} ${unit}`.trim());
  const delta=filter==='declin'?(reading.value/reference-1)*100:reading.value-reference;
  lines.push(`${c.difference}: ${formatHoverNumber(delta,locale,true,2)} ${filter==='declin'?'%':flood?c.points:unit}`.trim());
 }
 return {...c,valuesLabel:c.localValues,measure:filter==='declin'?c.countryPopulation:flood?c.floodShare:human.definitions[filter],comparison,values:lines.join('\n')};
}
export function legendCopy(filter,locale,mode){
 const c=readingCopy(locale),changing=mode!=='value',diverging=changing||filter==='stabilite';
 const pairs={chaleur:[c.cooler,c.warmer],stabilite:[c.cooler,c.warmer],feux:[c.fewer,c.moreDays],secheresse:changing?[c.wetter,c.drier]:[c.drier,c.wetter],mer:[c.lessFlood,c.moreFlood],fleuves:[c.lessFlood,c.moreFlood],declin:changing?[c.growing,c.shrinking]:[c.lessDecline,c.moreDecline]};
 const ticks=pairs[filter]||[];
 return {ticks:diverging?[ticks[0],c.same,ticks[1]]:ticks,caption:filter==='declin'&&mode==='value'?c.populationCaption:mode==='reference'||filter==='stabilite'&&mode==='value'?c.historicalMode:mode==='change'?c.change:c.valueMode};
}
