export const copy = {
  en: {
    title: 'fromearth / 2050 — Museums & institutions',
    description: 'Bring fromearth into your museum, exhibition or learning space. Create an experience around climate science, your own data and the world future generations will inherit.',
    ogTitle: 'fromearth — The future. A shared experience.',
    ogDescription: "Interactive experiences for museums, institutions and future generations. Let's build one together.",
    skip: 'Skip to content', navigation: 'Main navigation', pageLanguage: 'Page language', possibilities: 'The possibilities', yourData: 'Your data', contact: 'Contact us',
    audience: 'For museums, institutions & places of learning', hero1: 'The future.', hero2: 'A shared', hero3: 'experience.',
    lead: 'Bring climate science into your space. Help people connect the places they love with the world future generations will inherit.',
    create: "Let's create it together", explore: 'Explore fromearth', created: 'An experience by', idea: 'From an idea by Robin Mahieux.',
    artAlt: 'A false-colour satellite image of the Lena River Delta', artCaption: 'Lena Delta · USGS / NASA satellite imagery. Colours do not represent temperatures.',
    impactTitle: 'A connection that lasts.', impactIntro: 'For the people here today. And those who come next.',
    impactStatement: 'Start with a place someone cares about. Open a conversation about the future we share.',
    impactBody: 'A child discovering their hometown. A family comparing generations. A community exploring how its landscape could change. fromearth turns scientific information into a shared moment of curiosity, understanding and conversation.',
    impactAim: 'Together, we can build an experience that supports your learning goals and gives visitors something to carry beyond the exhibition: questions, new perspectives and a reason to keep exploring.',
    demoTitle: 'Begin with the experience.', demoLink: 'Try the interactive globe', videoLabel: 'Recorded walkthrough of the fromearth interface',
    demoCaption: 'Recorded from the fromearth web experience. Exhibition formats are developed with each partner.',
    formatsTitle: 'Your space. Our starting point.', formatsIntro: 'A website, a touch screen or an immersive installation. We shape the format around your audience.',
    licenceTitle: 'Bring fromearth to your venue.', licenceType: 'License an existing experience', licenceBody: 'Adapt fromearth for your website or an interactive display. Focus on the places that matter to your visitors, with a guided introduction and a format suited to your setting.', licenceLink: 'Discuss a licence',
    commissionTitle: 'Tell a story only you can tell.', commissionType: 'Commission a new experience', commissionBody: 'Build around your research, collections or local data. fromanother brings art direction, interaction and storytelling to an experience shaped with your curatorial and scientific teams.', commissionLink: 'Discuss your project',
    partnershipTitle: 'Imagine something bigger, together.', partnershipType: 'Co-create a partnership', partnershipBody: 'Develop a shared exhibition or immersive installation. We can explore funding partners, touring formats and shared ticketing where they fit the project.', partnershipLink: 'Explore a partnership',
    dataTitle: 'Your data has a story.', dataIntro: "Let's give people a way to explore it.", dataStatement: 'Your research.\nYour territory.\nYour perspective.',
    dataBody: 'Have your own datasets, environmental observations or research? We can develop an adaptation around them, alongside selected fromearth layers or as a dedicated experience.',
    dataProcess: 'Together, we review what the data can support, agree on its sources and permissions, and design how visitors explore it. Your team contributes the knowledge; we help make it tangible.',
    dataLimits: 'Integration is scoped with each partner. Sources, scenarios, units and uncertainties remain visible. Climate projections describe possible futures, not exact predictions for a street or a building.',
    approachTitle: 'Designed for learning. Made for people.', approachIntro: 'We begin with what your visitors should discover.',
    learningTitle: 'A clear learning purpose', learningBody: 'Define the questions, concepts and conversations the experience should support with your education team.',
    accessTitle: 'An invitation to participate', accessBody: 'Plan language, legibility, interaction and accessibility around your audience and venue.',
    connectionTitle: 'Room for connection', connectionBody: 'Create moments for families, school groups and communities to explore and discuss together.',
    beyondTitle: 'Beyond the visit', beyondBody: 'Explore a companion web experience or learning resources that let the conversation continue at home and in the classroom.',
    contactTitle: 'What could we create together?', contactBody: "Tell us about your institution, your audience and the change you want to inspire. We'll explore the right format and collaboration with you.",
    briefTitle: 'A few details to start.', briefInstitution: 'Your institution, venue and location', briefAudience: 'Your audience and learning goals', briefFormat: 'The format and dates you have in mind', briefData: 'Your own data or themes to explore', briefBudget: 'An indicative budget, if you have one', briefNote: 'Each collaboration is scoped individually. Equipment, travel and installation are discussed separately.',
    aboutTitle: "Who we are.",
    aboutIntro: "Artists and storytellers creating shared experiences.",
    aboutBody: "fromanother is an artist-led creative studio founded by Vicki Dang and Robin Mahieux. We bring together film, 3D art, design and creative technology to create digital and immersive experiences for institutions, cultural spaces and brands.",
    aboutApproach: "Our work begins with a story and the people it is for. We collaborate with curatorial, scientific and education teams to turn complex ideas into experiences that invite curiosity and connection.",
    aboutLink: "Meet fromanother",
    press: 'Press & media', top: 'Back to top', subject: 'fromearth — Institutional partnership',
    emailBody: 'Hello fromanother,\n\nWe would like to explore a fromearth collaboration.\n\nInstitution / venue / location:\nAudience and learning goals:\nFormat and dates:\nOur data or themes:\nIndicative budget:\n\nBest regards,',
  },
  fr: {
    title: 'fromearth / 2050 — Musées & institutions',
    description: 'Invitez fromearth dans votre musée, exposition ou lieu d’apprentissage. Créons une expérience autour du climat, de vos données et du monde que recevront les générations futures.',
    ogTitle: 'fromearth — Le futur. Une expérience collective.',
    ogDescription: 'Des expériences interactives pour les musées, les institutions et les générations futures. Créons la vôtre ensemble.',
    skip: 'Aller au contenu', navigation: 'Navigation principale', pageLanguage: 'Langue de la page', possibilities: 'Les possibilités', yourData: 'Vos données', contact: 'Contactez-nous',
    audience: 'Pour les musées, les institutions et les lieux d’apprentissage', hero1: 'Le futur.', hero2: 'Une expérience', hero3: 'collective.',
    lead: 'Invitez les sciences du climat dans votre lieu. Reliez les endroits qui comptent pour vos visiteurs au monde que recevront les générations futures.',
    create: 'Créons-la ensemble', explore: 'Explorer fromearth', created: 'Une expérience de', idea: 'Une idée de Robin Mahieux.',
    artAlt: 'Image satellite en fausses couleurs du delta de la Lena', artCaption: 'Delta de la Lena · Image satellite USGS / NASA. Les couleurs ne représentent pas des températures.',
    impactTitle: 'Un lien qui dure.', impactIntro: 'Pour celles et ceux d’aujourd’hui. Et les générations à venir.',
    impactStatement: 'Partir d’un lieu qui compte. Ouvrir une conversation sur notre avenir commun.',
    impactBody: 'Un enfant qui découvre sa ville. Une famille qui croise les générations. Une communauté qui explore l’évolution possible de son paysage. fromearth transforme l’information scientifique en un moment partagé de curiosité, de compréhension et de dialogue.',
    impactAim: 'Ensemble, créons une expérience qui sert vos objectifs pédagogiques et accompagne vos visiteurs au-delà de l’exposition : des questions, de nouvelles perspectives et l’envie de continuer à explorer.',
    demoTitle: 'Tout commence par l’expérience.', demoLink: 'Essayer le globe interactif', videoLabel: 'Parcours enregistré dans l’interface de fromearth',
    demoCaption: 'Enregistrement de l’expérience web fromearth. Les formats d’exposition sont développés avec chaque partenaire.',
    formatsTitle: 'Votre lieu. Notre point de départ.', formatsIntro: 'Un site web, un écran tactile ou une installation immersive. Le format se construit autour de votre public.',
    licenceTitle: 'Accueillez fromearth chez vous.', licenceType: 'Une expérience sous licence', licenceBody: 'Adaptez fromearth à votre site ou à un dispositif interactif. Mettez en lumière les lieux qui comptent pour vos visiteurs, avec une introduction guidée et un format adapté à votre espace.', licenceLink: 'Parlons de licence',
    commissionTitle: 'Racontez votre propre histoire.', commissionType: 'Une création sur commande', commissionBody: 'Partez de vos recherches, de vos collections ou de vos données locales. fromanother apporte direction artistique, interaction et narration, en collaboration avec vos équipes scientifiques et de médiation.', commissionLink: 'Parlons de votre projet',
    partnershipTitle: 'Imaginons plus grand, ensemble.', partnershipType: 'Un partenariat de co-création', partnershipBody: 'Développons une exposition commune ou une installation immersive. Partenaires de financement, formats itinérants et billetterie partagée peuvent être étudiés selon le projet.', partnershipLink: 'Explorons un partenariat',
    dataTitle: 'Vos données ont une histoire.', dataIntro: 'Donnons au public un moyen de l’explorer.', dataStatement: 'Vos recherches.\nVotre territoire.\nVotre regard.',
    dataBody: 'Vous disposez de jeux de données, d’observations environnementales ou de recherches ? Nous pouvons développer une adaptation autour de vos contenus, avec certains calques fromearth ou dans une expérience dédiée.',
    dataProcess: 'Ensemble, nous examinons ce que les données permettent de raconter, leurs sources et leurs droits d’utilisation, puis concevons le parcours de découverte. Votre équipe apporte le savoir ; nous aidons à le rendre tangible.',
    dataLimits: 'L’intégration est définie avec chaque partenaire. Sources, scénarios, unités et incertitudes restent visibles. Les projections climatiques décrivent des futurs possibles, pas des prévisions exactes pour une rue ou un bâtiment.',
    approachTitle: 'Apprendre. Ressentir. Partager.', approachIntro: 'Partons de ce que vos visiteurs devraient découvrir.',
    learningTitle: 'Une intention pédagogique claire', learningBody: 'Définir avec votre équipe les questions, les notions et les échanges que l’expérience doit accompagner.',
    accessTitle: 'Une invitation à participer', accessBody: 'Penser les langues, la lisibilité, les interactions et l’accessibilité selon votre public et votre lieu.',
    connectionTitle: 'Une place pour le collectif', connectionBody: 'Créer des moments pour explorer et échanger en famille, avec une classe ou au sein d’une communauté.',
    beyondTitle: 'Au-delà de la visite', beyondBody: 'Envisager une expérience web complémentaire ou des ressources pédagogiques pour prolonger le dialogue à la maison et en classe.',
    contactTitle: 'Que pourrions-nous créer ensemble ?', contactBody: 'Parlez-nous de votre institution, de votre public et du changement que vous souhaitez inspirer. Explorons ensemble le format et la collaboration qui vous correspondent.',
    briefTitle: 'Quelques détails pour commencer.', briefInstitution: 'Votre institution, votre lieu et sa localisation', briefAudience: 'Votre public et vos objectifs pédagogiques', briefFormat: 'Le format et les dates envisagés', briefData: 'Vos données ou les thèmes à explorer', briefBudget: 'Un budget indicatif, si vous en avez un', briefNote: 'Chaque collaboration fait l’objet d’un périmètre adapté. Matériel, déplacements et installation sont discutés séparément.',
    aboutTitle: "Qui sommes-nous ?",
    aboutIntro: "Des artistes et des récits pour créer des expériences collectives.",
    aboutBody: "fromanother est un studio de création fondé par Vicki Dang et Robin Mahieux. Nous réunissons cinéma, art 3D, design et technologies créatives pour concevoir des expériences numériques et immersives destinées aux institutions, aux lieux culturels et aux marques.",
    aboutApproach: "Notre travail commence par une histoire et les personnes qui vont la vivre. Nous collaborons avec les équipes de médiation, de recherche et de création pour rendre les idées complexes accessibles et susciter curiosité et lien.",
    aboutLink: "Découvrir fromanother",
    press: 'Presse & médias', top: 'Retour en haut', subject: 'fromearth — Partenariat institutionnel',
    emailBody: 'Bonjour fromanother,\n\nNous souhaitons explorer une collaboration autour de fromearth.\n\nInstitution / lieu / localisation :\nPublic et objectifs pédagogiques :\nFormat et dates :\nNos données ou thèmes :\nBudget indicatif :\n\nBien cordialement,',
  },
};
