import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const out=new URL('file://' + fs.mkdtempSync('/tmp/terra-links-') + '/');fs.mkdirSync(out,{recursive:true});const results=[];
const browser=await chromium.launch({executablePath:chromium.executablePath()});
try{
const c=await browser.newContext({permissions:['clipboard-read','clipboard-write'],locale:'en-US'});await c.addInitScript(()=>Object.defineProperty(navigator,'share',{value:undefined}));const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.URL0||'http://localhost:8080/';
await p.goto(base);await p.waitForSelector('#voile.pret');await p.click('#bouton-entree');await p.waitForTimeout(2000);await p.click('#champ-recherche');await p.fill('#champ-recherche','Seville');await p.getByRole('option').filter({hasText:'Seville'}).first().click();await p.waitForTimeout(4200);await p.locator('#curseur').focus();await p.keyboard.press('End');await p.click('#dossier-partage');const clipboard=await p.evaluate(()=>navigator.clipboard.readText());assert.ok(clipboard.includes('an=2050'));const link=clipboard.match(/https?:[^\s]+/)[0];await p.goto(link);await p.reload();await p.waitForSelector('#voile.pret');await p.click('#bouton-entree');await p.waitForTimeout(2500);assert.equal(await p.locator('#champ-recherche').inputValue(),'Seville');assert.equal(await p.locator('#curseur').inputValue(),'2050');results.push({name:'actual clipboard city link round trip',pass:true,clipboard});
await p.click('#dossier-croix');await p.click('#bouton-reglages');await p.click('#bouton-partager');const globalLink=await p.evaluate(()=>navigator.clipboard.readText());assert.ok(globalLink.includes(base));assert.ok(!globalLink.includes('#v='));results.push({name:'share Terra clipboard link',pass:true,clipboard:globalLink});
for(const hash of ['#v=Paris&cc=FR&an=oops','#v=Paris&cc=FR&an=9999','#v=%E0%A4%A&an=2050','#v=NeverExists&an=2040']){
 await p.goto(base+hash);await p.reload();await p.waitForSelector('#voile.pret');await p.click('#bouton-entree');await p.waitForTimeout(2500);const year=Number(await p.locator('#curseur').inputValue());assert.ok(year>=2026&&year<=2050);if(hash.includes('9999'))assert.equal(year,2050);if(hash.includes('NeverExists')||hash.includes('%E0'))assert.equal(await p.locator('#dossier').evaluate(e=>e.classList.contains('ouvert')),false);results.push({name:'invalid deep link '+hash,pass:true,year});}
assert.deepEqual(errors,[]);results.push({name:'no page errors',pass:true});
}catch(e){results.push({pass:false,error:e.message});}finally{await browser.close();}fs.writeFileSync(new URL('results.json',out),JSON.stringify(results,null,2));console.log(JSON.stringify(results));process.exitCode=results.some(x=>!x.pass)?1:0;
